global:
  resolve_timeout: 5m
  smtp_from: haimianguma@foxmail.com
  smtp_auth_username: haimianguma@foxmail.com
  smtp_auth_password: 
  smtp_require_tls: false
  smtp_smarthost: 'smtp.qq.com:465'

route:
  receiver: 'email-alert'
  group_by: ['job']
 
 
  routes:
  - receiver: 'email-alert'
    # When a new group of alerts is created by an incoming alert, wait at
    # least 'group_wait' to send the initial notification.
    # This way ensures that you get multiple alerts for the same group that 
    #start firing shortly after another are batched together on the first 
    # notification.
    group_wait: 50s
    # When the first notification was sent, wait 'group_interval' to send a 
    # batch of new alerts that started firing for that group.  
    group_interval: 5m
    # If an alert has successfully been sent, wait 'repeat_interval' to
    # resend them.
    repeat_interval: 12h
 
receivers:
- name: email-alert
  email_configs:
  - to: haimianguma@foxmail.com